### ISSUE TITLE
The github repo version is a lot slower at generating entropy than the app on the AppStore

### ISSUE THREAD

**Issue by Wandering-Consciousness** [vault12/TrueEntropy#1]
I'd first just like to say thank you very much for this awesome app and making it open source. It's just what I was looking for. Plus your article on Medium is really well written.

I cloned the repo and got the app running on my device but it seems to be a lot slower at generating entropy compared to the app on the AppStore. Does this GitHub repo have the same source or are there some updates you decided not to commit?

To get the project compiling and running under the latest version (iOS 13 / Xcode 11.3 / Swift 5) I had to make some minor UI-related tweaks but nothing that should've affected the entropy generating logic. I did also remove the cocoapods dependencies (Sodium) etc because I don't need the ability to upload it. 

I know it's been a couple of years since this was worked on, but if you could give me any help that would be much appreciated. Likewise, if there's any more info you need from me please do ask.

**Comment by lord-max** [comment]
The speed difference between debug and release build is big. Entropy post-processing is very CPU intensive, with a lot of buffers/objects required, so adding debugging harness to all intrinsic Swift objects adds a lot of overhead on such math-heavy code. Try to run a release build and you probably will see much faster generation.

**Comment by Wandering-Consciousness** [comment]
Ah, that was it! Simple. Thank you.
