### ISSUE TITLE
Can not compile TrueEntropy

### ISSUE THREAD

**Issue by thebitbrine** [vault12/TrueEntropy#2]
I am trying to build TrueEntropy in Xcode 11.3 in Swift 4/5 but no matter what I try I can't get it to compile.
First, the ```Sodium``` package was missing the ```libsodium``` library so I edited the Podfile and added ```libsodium``` there and ran ```pod install```, and that fixed the missing ```libsodium``` library issue.
I have tried to compile this on different machines, Xcode, Swift, and iOS versions, but nothing seems to matter.
Here's a screenshot of what's exactly happening in my Xcode after running the ```pod install```

![Xcode](https://i.imgur.com/2fcT8kY.png)

**Comment by thebitbrine** [comment]
After a few hours of rewriting, I finally got it to compile, but I removed the ```GlowLite``` library because it had too many errors and I didn't need it anyway.
I think this code needs a refresh because honestly it is an amazing program but it sucks that it won't compile.
I'm not going to close this because it is not solved yet.

**Comment by pavlo-liapin** [comment]
@thebitbrine thanks for your feedback!
@dmitry-salnikov updated this project to support Swift 5 and the latest Xcode environment, so you are welcome to participate. Feel free to open more issues or PRs. For now, I'm closing this ticket.
